### ISSUE TITLE
Interpreting the MMDB_lookup_result_s.netmask for IPv4

### ISSUE THREAD

**Issue by jroyalty** [maxmind/libmaxminddb#105]
It seems when doing a lookup using an IPv4 address that the resulting netmask is incorrect.  I noticed that if I subtract the database's (the city DB, at least) value of `ipv4_start_node.netmask` from the result I get a netmask value I expect.  Here's some example code that elucidates the issue:

```c
#include <stdio.h>
#include <stdlib.h>
#include <maxminddb.h>

int main(int argc, const char * argv[]) {
    MMDB_s *mmdb = (MMDB_s *)malloc(sizeof(MMDB_s));
    MMDB_open("/tmp/GeoIP2-City_20160105/GeoIP2-City.mmdb",
              MMDB_MODE_MMAP, mmdb);
    
    int gai_error = 0;
    int mmdb_error = MMDB_SUCCESS;
    MMDB_lookup_result_s res = MMDB_lookup_string(mmdb, "71.183.42.223", &gai_error, &mmdb_error);
    
    // Result from legacy database is:  71.183.42.223 = 24
    // The following returns:  Netmask as returned: 120, corrected: 24
    printf("Netmask as returned: %d, corrected: %d\n", res.netmask, res.netmask - mmdb->ipv4_start_node.netmask);
    
    return 0;
}
```
The question is:  Should I be doing this subtraction myself or should the library be returning the netmask value already corrected as such?

**Comment by autarch** [comment]
This is a bug in the library for sure.

**Comment by autarch** [comment]
So after discussing this some more we're not so sure if this is a bug. If you're looking up an IPv4 address in an IPv6 databse than the netmask is arguably right as-is, since it's the right netmask for the IPv6 address space.

**Comment by jroyalty** [comment]
Thanks for the follow-up.  That makes sense.

What's the recommended way to determine netmask for an IPv4 address in IPv6 databases?  Does it make sense to have something more official than subtracting `ipv4_start_node.netmask`?

**Comment by autarch** [comment]
You can just subtract 96, I think. `128 - 32 = 96`

**Comment by jroyalty** [comment]
Thanks for the info.

**Comment by oschwald** [comment]
I am going to re-open this as we should really improve the documentation to be more explicit.
