### ISSUE TITLE
Installing gem -v 0.1.2 complains of "Missing libmaxminddb"

### ISSUE THREAD

**Issue by alexneigher** [maxmind/libmaxminddb#106]
Despite having libmaxminddb properly installed on my system, it still errors like:
`checking for maxminddb.h... no`
`Missing libmaxminddb`

Cannot get the gem to install. 
This potentially could be an issue with libmaxminddb 1.1.4 (most recent).

**Comment by oschwald** [comment]
I am not sure which Gem you are using, but it would be better to file this issue in the bug tracker for it rather than here.
