### ISSUE TITLE
libmaxminddb provides an API for getting the MMDB_entry_s associated with a given record's value

### ISSUE THREAD

**Issue by autarch** [maxmind/libmaxminddb#110]
This should be added to **the end** of the `MMDB_search_node_s` struct that is populated by `MMDB_read_node`.

AC:
* A new publicly accessible set of defines is created:
    * `MMDB_RECORD_TYPE_SEARCH_NODE (0)`
    * `MMDB_RECORD_TYPE_EMPTY (2)`
    * `MMDB_RECORD_TYPE_DATA (2)`
* The struct should be extended by adding the following fields:
    * `uint8_t right_record_type`
    * `uint8_t left_record_type`
    * `MMDB_entry_s right_record_entry`
    * `MMDB_entry_s left_record_entry`
* The `MMDB_entry_s` value is only populated if record is a data record.

**Comment by oschwald** [comment]
Are we doing an enum rather than `#define`? I'd generally prefer enums for this use case, but all of our other similar values are done using the pre-processor.

**Comment by autarch** [comment]
Doh, yeah, I meant a `#define`.
