### ISSUE TITLE
Please provide a way for users to mmap databases with different mmap options or madvise settings

### ISSUE THREAD

**Issue by rafl** [maxmind/libmaxminddb#112]
The `mmap`ping done by this library is currently very opaque to the user. It's not easily possible to give the kernel any hints about memory management using the various `mmap` flags or `madvise` on the `mmap`ed region.

Exposing options to do so might allow users to tune the libraries behaviour for their use case.

**Comment by oschwald** [comment]
We tested this and decided it was not practical.
