### ISSUE TITLE
GeoIP Apache Installation Issues

### ISSUE THREAD

**Issue by ranjania** [maxmind/libmaxminddb#115]
Hi,
Im trying to install GeoIP for apache to read from an mmdb database on solaris. I have installed libmaxminddb and im trying to install the below geoIP2 for apache using the below commands

git clone --recursive https://github.com/maxmind/mod_maxminddb
./bootstrap
./configure  (successful)
make install 

when i execute make install command i get the below error:

Making all in src
/usr/bin/apxs -c  -lmaxminddb  -Wc,"-g -O2 -std=c99 -fms-extensions"  mod_maxminddb.c
/usr/apr/1.3/build/libtool --silent --mode=compile cc -prefer-pic -m32 -xO4 -xtarget=ultra2 -xarch=sparcvis -xchip=ultra2 -Qoption cg -xregs=no%appl -W2,-xwrap_int -xmemalign=8s -mt -DSSL_EXPERIMENTAL -DSSL_ENGINE  -DSOLARIS2=11 -D_POSIX_PTHREAD_SEMANTICS -mt -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/apache2/2.2/include  -I/usr/apr/1.3/include   -I/usr/apr-util/1.3/include -I/usr/include/openldap -g -O2 -std=c99 -fms-extensions  -c -o mod_maxminddb.lo mod_maxminddb.c && touch mod_maxminddb.slo
env: No such file or directory
apxs:Error: Command failed with rc=65536
.
*** Error code 1
make: Fatal error: Command failed for target `module'

Can you please let me know what im  missing?

Thanks

**Comment by ranjania** [comment]
Please note that i have installed libtool and it is available in the location /usr/apr/1.3/build/libtool

**Comment by ranjania** [comment]
Do you think that this is because i have installed the gcc compiler on Solaris 11 ? Can i execute make command using the gcc compiler? i dont have the sun c compiler installed.

**Comment by oschwald** [comment]
Yes, this is likely related to using Solaris. I am not sure what you are missing offhand. You might have better luck asking on StackOverflow, tagging the issue with both the Solaris and Apache tags.

I'd be interested in any solution you find.

**Comment by ranjania** [comment]
I tried executing the below command explicitly on the command line
/usr/apr/1.3/build/libtool --silent --mode=compile cc -prefer-pic -m32 -xO4 -xtarget=ultra2 -xarch=sparcvis -xchip=ultra2 -Qoption cg -xregs=no%appl -W2,-xwrap_int -xmemalign=8s -mt -DSSL_EXPERIMENTAL -DSSL_ENGINE  -DSOLARIS2=11 -D_POSIX_PTHREAD_SEMANTICS -mt -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/apache2/2.2/include  -I/usr/apr/1.3/include   -I/usr/apr-util/1.3/include -I/usr/include/openldap -std=gnu99 --tag=CC target-gcc -c -o src/mod_maxminddb.lo src/mod_maxminddb.c && touch src/mod_maxminddb.slo

This removed the apxs error and im still left with the below error:

env: No such file or directory

Have you come across this issue before? Im not sure which file/directory is not found.

**Comment by oschwald** [comment]
I am not sure. You could make sure everything is in your `$PATH` with the right name. As I mentioned, you are likely to have better luck on StackOverflow or a Solaris-specific forum.

**Comment by oschwald** [comment]
Closing as this involves [mod_maxminddb](https://github.com/maxmind/mod_maxminddb) rather than libmaxminddb. If you are still experiencing this issue, please open an issue there.
