### ISSUE TITLE
PPA outdated under Ubuntu 16.04

### ISSUE THREAD

**Issue by rwrnet** [maxmind/libmaxminddb#117]
Under Ubuntu 14.04, the ppa pulls:
Get:1 http://ppa.launchpad.net trusty InRelease [16.0 kB]
Get:2 http://ppa.launchpad.net trusty/main amd64 Packages [1912 B]

Which results in getting latest libmaxminddb

Under 16.04 the ppa pulls
Get:2 http://ppa.launchpad.net/maxmind/ppa/ubuntu xenial InRelease [16.3 kB]
Get:5 http://ppa.launchpad.net/maxmind/ppa/ubuntu xenial/main amd64 Packages [952 B]

Which results in getting version 1.1.0.

So newer ubuntu gets older version and vice versa. ;)

**Comment by oschwald** [comment]
Thanks. I copied the Wily binaries to Xenial, which should be sufficient until we do a new release.
