### ISSUE TITLE
Lost configure file?

### ISSUE THREAD

**Issue by matthewgao** [maxmind/libmaxminddb#118]
I didn't  see a configure file which mentioned in the Installation instruction.

**Comment by oschwald** [comment]
You need to download the prepared tarball to get the configure script, e.g., [libmaxminddb-1.2.0.tar.gz](https://github.com/maxmind/libmaxminddb/releases/download/1.2.0/libmaxminddb-1.2.0.tar.gz). If you check out the repo using git or use a GitHub generated tarball, you would first need to run `bootstrap`.
