### ISSUE TITLE
Documentation Example error

### ISSUE THREAD

**Issue by davidbenoit** [maxmind/libmaxminddb#124]
several errors in here: http://maxmind.github.io/libmaxminddb/ 

```
    MMDB_lookup_result_s result =
        MMDB_lookup_string(mmdb, ipstr, &gai_error, &mmdb_error);
```
should take in the ADDRESS of the mmdb:

```
    MMDB_lookup_result_s result =
        MMDB_lookup_string(&mmdb, ipstr, &gai_error, &mmdb_error);
```

Additionally:
- `fname` on line 6 isn't declared or initialized, I assume it would be `char *fname = argv[1]` after checking the number of arguments.
- line 58 should be consistent with line 20 using `ipstr`, which isn't assigned to anything, but I assume should be declared and initialized somewhere as `char * ipstr = argv[2]` after checking the number of arguments.

**Comment by oschwald** [comment]
Thanks! Several of these appear to have already been fixed in master but haven't made their way to the GitHub Page yet. That should happen next time we do a release. I have however made our use of `mmdb` more consistent throughout the docs in 00c1ab708deca6228509fba03dab0a900ed0a730.
