### ISSUE TITLE
./bootstrap: line 7: autoreconf: command not found

### ISSUE THREAD

**Issue by gabayliran** [maxmind/libmaxminddb#128]
`centos-release-7-2.1511.el7.centos.2.10.x86_64`
`nginx-1.10.2`

`git clone --recursive https://github.com/maxmind/libmaxminddb`

> After cloning, run ./bootstrap from the libmaxminddb directory and then follow the instructions for installing from a tarball as described above

`cd /root/libmaxminddb`
`[root@geo libmaxminddb]# ./bootstrap`
`./bootstrap: line 7: autoreconf: command not found`

Any help would be appreciated,
Thanks!

**Comment by gabayliran** [comment]
```
yum install -y autoconf
./bootstrap
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal  --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
```

**Comment by oschwald** [comment]
If you download the prepared distribution, e.g., [libmaxminddb-1.2.0.tar.gz](https://github.com/maxmind/libmaxminddb/releases/download/1.2.0/libmaxminddb-1.2.0.tar.gz), you shouldn't need to run `bootstrap` at all.
