### ISSUE TITLE
Building threads_t.exe using MSVC

### ISSUE THREAD

**Issue by gvanem** [maxmind/libmaxminddb#129]
I've managed to built everything in libmaxminddb using MSVC-2015 except for this `t/threads_t`  program. Du to the non-standards use of variable-sized local-arrays:

``` c
 void run_ipX_tests(MMDB_s *mmdb, const char *pairs[][2], int pairs_rows,
                    int mode, const char *mode_desc)
 {
    pthread_t threads[pairs_rows];
    struct thread_arg thread_args[pairs_rows];
```

I've patched it into:

``` diff
--- a/t/threads_t.c 2014-01-29 00:09:53
+++ b/t/threads_t.c 2016-10-27 12:13:28
@@ -1,4 +1,5 @@
 #include "maxminddb_test_helper.h"
+#include <assert.h>
 #include <pthread.h>

 typedef struct thread_arg {
@@ -117,11 +118,15 @@
        result->ip_looked_up, mode_desc);
 }

+#define PAIRS_ROWS 18
+
 void run_ipX_tests(MMDB_s *mmdb, const char *pairs[][2], int pairs_rows,
                    int mode, const char *mode_desc)
 {
-    pthread_t threads[pairs_rows];
-    struct thread_arg thread_args[pairs_rows];
+    pthread_t threads[PAIRS_ROWS];
+    struct thread_arg thread_args[PAIRS_ROWS];
+
+    assert (pairs_rows <= PAIRS_ROWS);

     for (int i = 0; i < pairs_rows; i += 1) {
         thread_args[i].thread_id = i;
```

and it seems to work fine. How about it?

**EDIT** I'd rather have used `alloca()` above.

PS. I used a 4 year old version of Ross Johnson's excellent Pthreads-Win32.

**Comment by oschwald** [comment]
Using `alloca()` seems like it would probably be fine given that MSVC doesn't support C99 VLAs. It would be nice to fix up our [Visual Studio](https://github.com/maxmind/libmaxminddb/tree/master/projects) build files to include the threads test so that we don't break it in the future.

**Comment by gvanem** [comment]
>  It would be nice to fix up our Visual Studio build files to include the threads test

And maybe add `getopt()` too?

**Comment by gvanem** [comment]
Except for the missing `getopt_long()` for MSVC /clang-cl, this issue is fixed. 
Hence closing due to lack of progress.
