### ISSUE TITLE
undefined reference to `rpl_malloc'

### ISSUE THREAD

**Issue by piranna** [maxmind/libmaxminddb#144]
I'm compiling `libmaxminddb` statically as a vendor library in my source code using cmake (I was dictated to don't include more external dependencies, including package manager ones...), and when compiling on my CI servers i get just only a `undefined reference to `rpl_malloc'` error when compiling `libmaxminddb` files. On my machine it compiles flawlessly, but after doing a repo clean-up and compile again from scratch, it compiles but when running the tests I get a core dump at the very beginning. Any clue about what could be happening or what could I do?

**Comment by oschwald** [comment]
I am not sure offhand, but doing a Google search for `rpl_malloc` reveals several different suggests that may be useful.

**Comment by rgerhards** [comment]
I can dig out details if useful, but I remember that this is caused by problems in autoconf MALLOC detection which does not work with all compilers/versions (clang IIRC). My solution for the rsyslog project was to remove that from configure.ac. Done over 2 years ago without any problems.

**Comment by rgerhards** [comment]
I thought I quickly check and craft a PR ;-)

**Comment by jacobpewit** [comment]
I had this problem recently and I solved it like this:
`ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ./configure --with-gnu-ld`
