### ISSUE TITLE
Search tree is corrupt

### ISSUE THREAD

**Issue by srguglielmo** [maxmind/libmaxminddb#148]
Hello,

I have a script that downloads the GeoIP2-City database and md5 checksum files, validates the checksum, then extracts the tarball. I am then running an application (GoAccess web stats) that uses the GeoIP database.

The application is printing an error stating the database is corrupt. I've manually verified the checksum and it does match, so I'm not sure what the problem is.

The script is downloading the files from
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz.md5

```
Fatal error has occurred
Error occured at: src/geoip2.c - geoip_lookup - 114
Error from libmaxminddb: The MaxMind DB file's search tree is corrupt
```

This is occurring on CentOS 7.

```
GeoIP.x86_64                         1.5.0-11.el7                @anaconda      
GeoIP-devel.x86_64                   1.5.0-11.el7                @base          
libmaxminddb.x86_64                  1.2.0-1.el7                 @epel          
libmaxminddb-devel.x86_64            1.2.0-1.el7                 @epel
```

Thanks,
Steve

**Comment by oschwald** [comment]
Are you sure GoAccess is using the right file? I tested the file with 1.2.0 and it seems to work fine for me. Are you able to successfully query the database using `mmdblookup`?

**Comment by srguglielmo** [comment]
Hi,

Thanks for the quick response. I double checked GoAccess's config and it is set to use the correct file. I am unable to use `mmdblookup`, however. See the output below.

Thanks,
Steve

> [user] ~/scripts $ ls -al
> total 74948
> drwxrwxr-x 2 user group      145 Nov  8 12:05 .
> drwx------ 8 user group      210 Nov  8 12:05 ..
> -rwxr--r-- 1 user group     1560 Nov  8 12:03 generate_webstats.sh
> -rw-rw-r-- 1 user group 52109949 Nov  8 12:05 GeoLite2-City.dat
> -rw-rw-r-- 1 user group 24618714 Nov  6 14:27 GeoLite2-City.tar.gz
> -rw-rw-r-- 1 user group       32 Nov  6 14:27 GeoLite2-City.tar.gz.md5
> -rwxrw-r-- 1 user group     1424 Nov  8 12:05 update_geoip_db.sh
> 
> [user] ~/scripts $ md5sum GeoLite2-City.tar.gz
> 5e05d79ea7f391506106f8b18aa8ef33  GeoLite2-City.tar.gz
> 
> [user] ~/scripts $ cat GeoLite2-City.tar.gz.md5 
> 5e05d79ea7f391506106f8b18aa8ef33
> 
> [user] ~/scripts $ mmdblookup --file GeoLite2-City.dat --ip 172.217.9.206
> 
>   Got an error from the maxminddb library: The MaxMind DB file's search tree is corrupt
> 
> [user] ~/scripts $ file GeoLite2-City.dat 
> GeoLite2-City.dat: data
> 
> [user] ~/scripts $ mmdblookup --version
> 
>   mmdblookup version 1.2.0
>

**Comment by oschwald** [comment]
I am a bit confused why your file is named `GeoLite2-City.dat`. The file name should be `GeoLite2-City.mmdb`.

**Comment by srguglielmo** [comment]
Ah! I **ass**umed that it was a single file in the tarball. My command to extract it was incorrect and caused the issue.

`/bin/tar -xzOf GeoLite2-City.tar.gz > GeoLite2-City.dat`

Sorry about that. If I extract it normally, I see the `mmdb` file now.
