### ISSUE TITLE
thread safety bug/restrictions?

### ISSUE THREAD

**Issue by rgerhards** [maxmind/libmaxminddb#151]
I use libmaxminddb in a highly threaded environment inside my rsyslog project. We have seen segfaults in code regions that use libmaxminddb. Using valgrind's helgrind thread debugger we found at least one data race where libmaxminddb accesses memory that had been passed back to a caller. The caller used the returned data. This use and one of the next calls lead to the race. Details are in our bug tracker (everything in front of the mentioned comment is probably not of interest, it's a very long issue):
https://github.com/rsyslog/rsyslog/issues/1885#issuecomment-344882616

I have researched the libmaxmindb is said to be thread-safe. My question now: is there a data race bug in libmaxminddb or do I do something that is not legally permitted when using the lib. Or more precisely: is it OK to hold on to data returned from libmaxminddb calls when doing the next one or do I need to copy it to a separate buffer?

**Comment by horgh** [comment]
Thank you for reporting this!

You should be able to hold on to the data returned by the functions. From looking at the rsyslog code calling libmaxminddb, it looks like a valid use.

I'm not sure what the exact problem is yet. I'm going to look into this further.

**Comment by horgh** [comment]
I wrote a quick program to run random lookups and dump out the results in multiple threads as is done in rsyslog. I'm not able to reproduce any similar races as shown by the helgrind output in the issue.

I do see a couple things worth pointing out in the code:

  - You should check that `entry.found_entry` is true before trying to look it up
  - It looks like you are parsing the output of `MMDB_dump_entry_data_list()` as JSON. It is not quite JSON. I'm not sure if this could be causing any issue.

I'm not sure that either of these would cause such behaviour though.

It is interesting that the race in the comment you linked is between a JSON function and this library's entry dump function. I can't explain that.

I do see a possible memory access issue that I'm looking into which could be related. However, the original rsyslog issue predates the version where I believe it would be coming from (1.3.0), so I am not sure it could be the original problem.

**Comment by ycflash** [comment]
Hi, I'm the reporter of the rsyslog 1885 issue, and I can confirm that the link mentioned here is using latest version 1.3.0.

The race condition occurs when rsyslog queue is very large (500,000 items), this is what I believe how these workflow go with my scenario:

step 1. rsyslog receive a message and extrat an IP
step 2. rsyslog use the IP to find geo location info using libmaxminddb
step 3. rsyslog construct an json (include use step 2 result) and queue it before send to ES
step 4. when ES if not available, rsyslog queue (step 3) will be hold upto 500,000 items, and when the queue full (or at a very large size) the race usually happens

I hope these info will help to understand how the race could happen.

**Comment by rgerhards** [comment]
If @ycflash agrees, I can do further experiments to track down the issue as far as rsyslog is concerned. I myself can unfortunately not reproduce the issue.

**Comment by ycflash** [comment]
Thanks @rgerhards , I'll do anything I can to help resolve this issue.

**Comment by horgh** [comment]
Thanks very much for the additional info. The debugging you both have carried out is impressive!

One thought would be to try the prior version of libmaxminddb (1.2.1) as well and see if that shows any difference. Was that the version you were using when you first encountered issues? I am tracking a problem that I think was introduced in 1.3.0, so this could be a variable to eliminate. If there's still a problem showing with 1.2.1, then there may be multiple things going on.

Related to the rsyslog plugin code, I had another thought: It might be good to abort early if `entry_data_list` or `memstream` are NULL, and also to check the result of `MMDB_dump_entry_data_list()`. I doubt these are causing a race, but might be good to be sure about.

Thanks for your help!

**Comment by ycflash** [comment]
The original issue 1885 of rsyslog is run with 1.1.4, as I recall the it may have the same race condition. And I'll redo a test to confirm if it has any difference, will feedback later on this.

**Comment by ycflash** [comment]
I have done some simple tests with libmaxminddb, and I don't find any race condition occurs. I think this confirms @horgh 's thought.

**Comment by rgerhards** [comment]
I don't outrule a problem on rsyslog's part, surely not. But we need to find where. It must be related to ommmdblookup, because if we single-thread it, all works. Let's see what the next test runs bring up.

**Comment by rgerhards** [comment]
@horgh Just a thought: I have seen you used Coverity scan in 2014. Would it be an idea to do a new scan run to see if it brings up something? Just an idea...

**Comment by ycflash** [comment]
I have finished a latest test round, logs posted here: [rsyslog 1885](https://github.com/rsyslog/rsyslog/issues/1885#issuecomment-346595254)

It seems libmaxminddb 1.2.1 & 1.3.0 both have race occurs, I hope you can find some useful info here.

**Comment by horgh** [comment]
Thanks for the testing and logs!

Yes, a Coverity scan is a great idea.

Regarding some of the noise in the 1.3.0 log: Possibly some of it is from a memory issue in that version that I mentioned yesterday. I'm working on a PR for it (#153). That makes the 1.2.1 logs a lot more interesting to me. As you say, there looks to be problems reported in that run as well. I'm not sure what to make of that yet.

**Comment by horgh** [comment]
I ran a Coverity scan on the current master and it showed nothing interesting.

**Comment by rgerhards** [comment]
@horgh - thanks! was at least worth a try...

**Comment by horgh** [comment]
Another thought: Are we guaranteed to have the database open when we're using the data returned by `MMDB_get_entry_data_list()`? That memory is safe for concurrent use, but the database must remain open.

From what I can tell [looking at your plugin](https://github.com/rgerhards/rsyslog/blob/i-1885-testing/plugins/mmdblookup/mmdblookup.c), we keep a database open per worker for its lifetime, so I think it is okay, but I thought I'd mention this as I'm not very familiar with how the plugins run.

An aside: Is a worker a single thread? You could in theory open the database once and share it between threads as well, rather than opening it potentially multiple times per process.

**Comment by rgerhards** [comment]
Assume that the rsyslog core works correctly (which is highly probable, but... ;-)) the database is opened on worker creation and closed on termination. At termination, no memory pointing into what was provided by libmaxminddb should be in use. In theory, messages may live a bit longer after worker termination, but the pulgin does some memory copies.

And, yes, a worker maps to exactly one thread. Workers are started and stopped based on rsyslog workload and configuration.

As a side-note, I inherited the plugin and wasn't very literate in regards to libmaxminddb. Very nice to get all this good advise! The ability to keep a single database connection accross workers is for sure useful - as are the others!
