### ISSUE TITLE
1.3.2 tarball contains build-time residue

### ISSUE THREAD

**Issue by dmacks** [maxmind/libmaxminddb#168]
t/.deps are files created at compile-time iff certain libtool options are enabled, and contain data highly specific to the local build machine. Therefore, they should not be included in a source release. I'm not sure if there is a 'make distclean' or similar target that has a bug, or some manual intervention was not documented or performed correctly, but libmaxminddb-1.3.2.tar.gz has t/.deps/*.Po that point to linux headers in /usr/include, which is definitely not correct for my darwin (OS X) machine.

**Comment by dmacks** [comment]
Cross-reference: [PR #126 at fink](https://github.com/fink/fink-distributions/pull/126)

**Comment by horgh** [comment]
Thank you for reporting this! I agree that we should exclude these from the tarballs. I'll leave this open until we fix it.
