### ISSUE TITLE
Enhance verbose-output of mmdblookup

### ISSUE THREAD

**Issue by joriws** [maxmind/libmaxminddb#172]
As IP is provided after -i command line parameter, it would great to be able to see on output which IP-mask it matched to provide answer from mmdb.

-f xxx.mmdb -i 192.168.1.1

returns something. I would like to know if IP matched to

192.0.0.0/8
192.168.0.0/16
192.168.1.0/24
192.168.1.0/29

etc. Because it has effect on accuracy, like geoip provide data only if mask is >20 or >24 or >29.. So I'd like to see where mmdblookup matched..

**Comment by BBcan177** [comment]
This would be a great feature to have! +1

**Comment by PatrickCronin** [comment]
We have recently released  [https://github.com/maxmind/mmdbinspect](`mmdbinspect`) which is a new tool intended to address several of the issues people raised relating to the general usability of `mmdblookup`. It supports querying multiple databases and multiple IPs with a single incantation, and it outputs pure JSON.

While the intent of `mmdblookup` was and is to support developers who are integrating libmaxminddb or other reader libraries into their applications, `mmdbinspect` is intended to be a well-behaved command line program supporting general purpose querying of MMDB databases.

It's in beta. We would welcome you to try it and provide any feedback you may have on its issues page.
