### ISSUE TITLE
Visual Studio 2017 Installation

### ISSUE THREAD

**Issue by luhar** [maxmind/libmaxminddb#173]
I am unable to install on Visual Studio 2017 as I am getting errors about missing the v120 toolset (VS 2013). I have tried both with and without retargeting to v141 toolset.

According to this [forum](https://social.msdn.microsoft.com/Forums/SECURITY/en-US/07ce397a-611b-4233-99b7-4b4bf6f58589/is-there-a-way-to-install-platform-toolset-v120-on-visual-studio-2017?forum=visualstudiogeneral), the only way to install the v120 toolset is to _also_ install VC++ 2013 since Build Tools 2013 does not include C++. Do you have any workarounds to doing this?

**Comment by nchelluri** [comment]
Hi,

You should be able to build it with Visual Studio Community 2013, which might be enough to get you over your hurdle, as it is available for free.

In the meantime we'll be looking into upgrading the Build Tools version but no word on when that'll get released yet.

**Comment by oschwald** [comment]
We now include a cmake build script that should allow for this.
