### ISSUE TITLE
Remove EU

### ISSUE THREAD

**Issue by maguri** [maxmind/libmaxminddb#175]
Please,

EU is not a country. I would like to know why does MaxMind return `Europe (EU)` as an ip origin.

Thanks,

**Comment by oschwald** [comment]
I assume you are referring to the GeoIP Legacy databases, not the GeoIP2 databases. With the Legacy databases, we would return EU in the country field when we did not have country-level data. If you don't want this behavior, I would suggest you upgrade to GeoIP2.

**Comment by maguri** [comment]
Thanks, I'll try and let you feedback
