### ISSUE TITLE
Declaration specifier expected near...

### ISSUE THREAD

**Issue by demyanovs** [maxmind/libmaxminddb#177]
Hi,
When I include file "local geo = require 'resty.maxminddb'" I get an error:
lua entry thread aborted: runtime error: .../resty_modules/lualib/resty/maxminddb.lua:115: declaration specifier expected near 'ssize_t' at line 73

My lua version: 5.1

Any idea why this error occurs?

**Comment by oschwald** [comment]
This sounds like a problem with the Lua library you are using rather than `libmaxminddb`. I would suggest you ask there.
