### ISSUE TITLE
Use CMake instead of autotools for building

### ISSUE THREAD

**Issue by zhuhaow** [maxmind/libmaxminddb#182]
Recently, I've been working on getting libmaxminddb onto Conan (https://github.com/zhuhaow/conan-libmaxminddb).

It's okay to use autotools on *nix, even cross-compiling for iOS. But it becomes quite difficult for windows (I get that few work with open source cares about windows, me either, and that simply makes things more painful when you have to support windows sometime). 

A VS2013 solution is provided, but that won't work out of the box on VS2017 #173. If target platform version is not specified, it will be default to windows sdk 8.1 which is not installed by default with VS 2017. To make it worse, there is no way to specify the latest installed Windows 10 SDK to use, you have to give a specific version number (which may be hundreds possibilities) and MS considers it as a feature not a bug, which I don't want to comment.

An other problem is that there is no way to change the static/dynamic build at build time, you have to create a project for each different settings. Unless libmaxminddb wants to use the libsodium way https://github.com/jedisct1/libsodium/tree/master/builds, where a solution file is provided for every vs version and projects for every possible config combinations, it is difficult to use the solution file provided.

Instead, using CMake makes since much simpler since there won't be two different sets of project management files. We can specify static/dynamic at build time without change a line in the cmake file. CMake will find the latest Windows SDK installed. It also has build-in support for configuring header file.

**Comment by geraldcombs** [comment]
Vcpkg has a bare-bones CMakeLists.txt at https://github.com/Microsoft/vcpkg/tree/master/ports/libmaxminddb. It only builds libmaxminddb (i.e. no mmdblookup and no tests) but it might make a good starting point.

I tried adding 

```
add_executable(mmdblookup bin/mmdblookup.c)
target_link_libraries(mmdblookup maxminddb)
```

but compilation failed due to the absence of getopt.
