### ISSUE TITLE
array out of bounds error (buffer overrun for read)

### ISSUE THREAD

**Issue by mlite** [maxmind/libmaxminddb#184]
There is an array out of bounds error triggerred by data_types_t test.

DTS_MSG: Stensal C/C++ DTS detected a fatal program error!
DTS_MSG: Continuing the execution will cause unexpected behaviors, abort!
DTS_MSG: Reading 293 bytes at 0xf6932a51 will read undefined values.
DTS_MSG: Diagnostic information:

- The object to-be-read (start:0xf6932000, size:2933 bytes) is allocated at
-     file:/home/sbuilder/workspace/libmaxminddb/src/maxminddb.c::397, 20
-  0xf6932000               0xf6932b74
-  +------------------------+
-  | the object  to-be-read |......
-  +------------------------+
-                          ^~~~~~~~~~
-      the read starts at 0xf6932a51 that is 292 bytes before the object end.
- Stack trace (most recent call first):
-[1]  file:/musl-1.1.10/src/string/strlen.c::88, 3
-[2]  file:/home/sbuilder/workspace/libmaxminddb/t/maxminddb_test_helper.c::28, 16
-[3]  file:/home/sbuilder/workspace/libmaxminddb/t/data_types_t.c::14, 30
-[4]  file:/home/sbuilder/workspace/libmaxminddb/t/data_types_t.c::396, 9
-[5]  file:/home/sbuilder/workspace/libmaxminddb/t/maxminddb_test_helper.c::63, 5
-[6]  file:/home/sbuilder/workspace/libmaxminddb/t/data_types_t.c::437, 5

**Comment by oschwald** [comment]
Thanks for reporting this! It appears limited to a test code.
