### ISSUE TITLE
The mmdblookup binary produces unusable JSON output

### ISSUE THREAD

**Issue by wjhendr** [maxmind/libmaxminddb#19]
Hi,

I am trying to use the **mmdblookup** tool from the command line and I'm having trouble parsing the output.  Specifically, the output seems to be ill-formatted JSON.

I'm running the latest version of the code.  Here's the command I'm running:

> bin/mmdblookup -f /usr/share/GeoIP/GeoLite2-City.mmdb -i 2.2.2.2 | python -mjson.tool

The above produces:

> Expecting , delimiter: line 6 column 19 (char 67)

I see that according to the _libmaxminddb_ man page:

> The  output  is formatted in a JSON-ish fashion, but values are marked with their data type (except for maps and arrays which are shown with "{}" and "[]" respectively).
> 
> The specific output format may change in future releases, so you should not rely on the specific formatting produced by this function.  It is intended to be used to show data to users in a readable way and for debugging purposes.

I can get further by replacing the _data type_ tags with commas using _sed_, e.g.:

> bin/mmdblookup -f /usr/share/GeoIP/GeoLite2-City.mmdb -i 2.2.2.2 | sed -e 's|<[^>]*>|,|g' | python -mjson.tool

but still no joy:

> Expecting property name: line 13 column 11 (char 203)

I'm in the process of writing a Perl script to clean up this output so that it can then be reliably parsed by JSON...but I feel like this would be easier/better if it the JSON was fixed by whatever produced it in the first place.  Of course, that may not be the goal of this tool, but that's what I'm after, anyway.

Thanks!

**Comment by PatrickCronin** [comment]
_Digging up the past a bit, but for posterity:_

We have recently released  [https://github.com/maxmind/mmdbinspect](`mmdbinspect`) which is a new tool intended to address several of the issues people raised relating to the general usability of `mmdblookup`. It supports querying multiple databases and multiple IPs with a single incantation, and it outputs pure JSON.

While the intent of `mmdblookup` was and is to support developers who are integrating libmaxminddb or other reader libraries into their applications, `mmdbinspect` is intended to be a well-behaved command line program supporting general purpose querying of MMDB databases.

It's in beta. We would welcome you to try it and provide any feedback you may have on its issues page.

**Comment by grahamatviewdeck** [comment]
No being funny, but why produce output which was obviously intended to be JSON then break it?
Why no just produce output in a completely different, and probably easier to code format?

**Comment by oschwald** [comment]
As mentioned above, this tool is intended to help those integrating the database into their application understand the structure of the records. As the database format allows both maps and arrays, the JSON-like syntax provides a widely understood method of displaying and distinguishing these elements.

As the output is not intended to be machine readable, it doesn't do any of the hard parts of JSON, such as properly escaping strings, or even simple things like not outputting trailing commas.

If you are looking for a command line tool to query MMDB databases, please look at [mmdbinspect](https://github.com/maxmind/mmdbinspect).
