### ISSUE TITLE
Ubuntu PPA does not include pkg-config configuration

### ISSUE THREAD

**Issue by martinslota** [maxmind/libmaxminddb#194]
The packages in the MaxMind PPA (https://launchpad.net/~maxmind/+archive/ubuntu/ppa) lack the `pkg-config` configuration file. Examples of such packages are

* `libmaxminddb-dev_1.3.2-0+maxmind1~trusty_amd64.deb`
* `libmaxminddb-dev_1.3.2-0+maxmind1~xenial_amd64.deb`

The corresponding official Ubuntu Cosmic packages contain the `libmaxminddb.pc` file:

https://packages.ubuntu.com/cosmic/amd64/libmaxminddb-dev/filelist

**Comment by oschwald** [comment]
Thanks for raising this. I uploaded new PPA packages that should fix the issue.
