### ISSUE TITLE
libta/tap.h: No such file or directory

### ISSUE THREAD

**Issue by alevesely** [maxmind/libmaxminddb#200]
When I hit that error, I [downloaded tap](https://github.com/zorgnax/libtap) and installed it.  However, it installed tap.h in `/usr/local/include`.  I notice it also installed a `tap.pc`, so maybe you could add `PKG_PROG_PKG_CONFIG` in `configure.ac`, and then set `CFLAGS` using `$PKG_CONFIG --cflags-only-I` or something similar.

As a workaround, I just changed `#include "libtap/tap.h"` with `#include <tap.h>`, and created a `libtap` directory with a dummy Makefile.  That way, make and make check succeeded.

**Comment by horgh** [comment]
Is this from a git clone? If so, you may need to clone the submodules as it is present as one.

e.g. with `--recursive`: `git clone --recursive https://github.com/maxmind/libmaxminddb`

**Comment by alevesely** [comment]
Sorry, it was release [1.3.2](https://github.com/maxmind/libmaxminddb/releases/tag/1.3.2).  Indeed, it looks rather like a git clone, as I had to run `autoreconf` to obtain a `configure` script.  Now I installed it and mmdblookup seems to work fine...
