### ISSUE TITLE
Out-of-source build fails

### ISSUE THREAD

**Issue by 17dec** [maxmind/libmaxminddb#201]
A normal `./configure && make` works fine, but trying to build from another directory does not. E.g.

```
mkdir x
cd x
../configure
make
```

Errors at this point:

```
cd libtap && make  all
/bin/sh: line 0: cd: libtap: No such file or directory
```

(The git submodules have been initialized & updated correctly.)

**Comment by oschwald** [comment]
Could you expand on the use case for this?

**Comment by 17dec** [comment]
It's a fairly common feature that allows for multiple builds on the same source. I use it when cross-compiling applications: Have a separate build directory for each architecture, all based on the same source directory. Saves creating multiple copies of the source.

Autotools supports out-of-source builds by default, but it's easy to break with custom make rules. It's more of a nice-to-have than a hard requirement, in any case.

**Comment by oschwald** [comment]
This should be possible with the new CMake build. I am not sure what would be necessary to make it work with the Autotools build, but PRs are welcome.
