### ISSUE TITLE
Memory leak of start_threaded_benchmark() in bin\mmdblookup.c

### ISSUE THREAD

**Issue by fightingyy** [maxmind/libmaxminddb#203]
![memory leak](https://user-images.githubusercontent.com/24968470/57744613-7f3c3880-76fc-11e9-98e8-9480ae1754ea.png)
Function start_threaded_benchmark() is defined in bin\mmdblookup.c.
Function start_threaded_benchmark() calls calloc() on line 629, and assigns a pointer which points to the start address to the variable tinfo. If the program executes to line 638 the function does not return, indicating that tinfo is not NULL and the space allocation is successful. Later, when start_time is equal to -1, the program returns without releasing tinfo on line 640, and a memory leak error has occurred. See the following code:

**Comment by oschwald** [comment]
Thanks. Mind making a PR for this? Given that the program exits after the function returns, the consequences seem pretty minimal, but it would be good to fix it in case the use changes in the future.

**Comment by oschwald** [comment]
Fixed in #204.
