### ISSUE TITLE
Allow retrieving the matching network

### ISSUE THREAD

**Issue by darix** [maxmind/libmaxminddb#207]
Companion bug for https://github.com/maxmind/mod_maxminddb/issues/81

The following ruby script 
```ruby
require 'maxminddb'
db = MaxMindDB.new('GeoLite2-ASN.mmdb')
p db.lookup('1.1.1.1')
```

gives me this output (reformatted for readability):

```
#<MaxMindDB::Result:0x000055a27cd962b8
  @raw={
    "autonomous_system_number"=>13335,
    "autonomous_system_organization"=>"Cloudflare, Inc.",
    "network"=>"1.1.1.0/24"
  }>
```

It would be awesome for the library to allow fetching this information as well. mod_maxminddb and the python-bindings could use it.

**Comment by oschwald** [comment]
It turns out that this information is already exposed as `netmask` in `MMDB_lookup_result_s`. I am going to close this issue as the `mod_maxminddb` change should be doable with no changes to `libmaxminddb`.

**Comment by darix** [comment]
Looking forward to have it exposed in mod_maxminddb and the python bindings then :)
