### ISSUE TITLE
Reading from Stream

### ISSUE THREAD

**Issue by jimyaghi** [maxmind/libmaxminddb#209]
I'm not sure if this is the right place to report the issue. I am using this library using the C extension with PHP. Using the library without the PHP extension allows me to read the database from a stream (i use google cloud storage for dynamic files). When i use the C extension, i am no longer able to read the file from a stream. Is this a known issue?

**Comment by oschwald** [comment]
This issue should be moved to the MaxMind DB Reader PHP repo. The fact that non-files work with the pure PHP version is accidental. If we were to implement such functionality in the C extension, it would be done in the C extension rather than `libmaxminddb`.
