### ISSUE TITLE
Error Message when installing package in R

### ISSUE THREAD

**Issue by deslaur** [maxmind/libmaxminddb#210]
> install_github("maxmind/libmaxminddb")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`maxmind`) and repo name (`libmaxminddb`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by oschwald** [comment]
I don't know what `install_github` is, but it is not a supported method of installing this library. I'd suggest you follow up with the author of that installer.
