### ISSUE TITLE
Add flag to make CLI output parsable as standard json / raw-values

### ISSUE THREAD

**Issue by pirate** [maxmind/libmaxminddb#212]
This ticket is for two very specific feature requests:

**1. When making top-level queries, there should be a way to get the output as standard JSON w/ commas, without type annotations or extra newlines.**
    There's no need to change the default behavior (although that would be ideal), to maintain backwards-compatibility, this can be added as a `--json` flag. This is needed to be parsable as actual JSON by tools like `jq`, and to be usable for any purpose in general without requiring lots of command-line `sed`/`awk` voodoo.  

```bash
$ mmdblookup --file /usr/local/var/GeoIP/GeoLite2-City.mmdb --json --ip 75.37.71.246
{ 
    "city": {
        "geoname_id": 5378538,
        "names": {
            "en": "Oakland",
            ...
        }
    },
    ...
}

# no preceding/trailing empty newlines, no type annotations, + commas added
# makes it usable directly with jq or as JSON, e.g. LOCATION="$(mmdblookup ... --json | jq '.city.names.en,.country.names.en')"
```

**2. When making queries for a specific value, there should be a way to get the value without extra newlines, quotes, or type annotations** (like `jq --raw-value` and many other tools).
    Once again, this is to make it usable in on the CLI / in scripts without requiring lots of `sed`/`awk` painfulness to strip the quotes, type annotation, and newline.

```bash
# if output is a single value, it can just write the plain value to stdout
$ mmdblookup --file /usr/local/var/GeoIP/GeoLite2-City.mmdb --raw-value --ip 75.37.71.246 city names en
Oakland

# no preceding/trailing empty newlines, no type annotations, no quotes (aka standard text, directly pipe-able without extra parsing)
# makes it usable in shell substitutions and many other places, e.g. CITY="$(mddblookup ... --raw-value)"
# (second layer of quotes + everything else makes this significantly harder as-is)

# if output is multiple values, whitespace-separated columns are very easy to parse with awk or other utilities, keys should be on each line to make it grep-able
# alternatively --raw-value could be limited to single-values and `exit 2` if there are multiple values (people can use --json + jq for handling multi-value queries)
$ mmdblookup --file /usr/local/var/GeoIP/GeoLite2-City.mmdb --raw-value --ip 75.37.71.246 city names
en:        Oakland
zh-CN:     奥克兰
...
```

**Reasoning for this feature request:**

This is otherwise a very nice tool, I appreciate the hard work so far and I'd love to be able to use it in a lot of places! But as evidenced by https://github.com/maxmind/libmaxminddb/issues/135, many people have spent a lot of hours trying to wrangle the output of `libmaxminddb` into a usable form. As it stands, the type-annotations-required mode provides negative utility for most use cases, and it seems like a pity to make CLI output un-parsable by pretty much all standard tooling without any flag to change that behavior.

> This is the Unix philosophy: Write programs that do one thing and do it well. Write programs to **work together**. Write programs to handle **text streams**, because that is a universal interface.

**Comment by PatrickCronin** [comment]
We have recently released  [`mmdbinspect`](https://github.com/maxmind/mmdbinspect) which is a new tool intended to address several of the issues people raised relating to the general usability of `mmdblookup`. It supports querying multiple databases and multiple IPs with a single incantation, and it outputs pure JSON.

While the intent of `mmdblookup` was and is to support developers who are integrating libmaxminddb or other reader libraries into their applications, `mmdbinspect` is intended to be a well-behaved command line program supporting general purpose querying of MMDB databases.

It's in beta. We would welcome you to try it and provide any feedback you may have on its issues page.

**Comment by PatrickCronin** [comment]
Closing issue as the requested feature is provided by `mmdbinspect`.
