### ISSUE TITLE
json answer part does not contain spaces in city name

### ISSUE THREAD

**Issue by rgerhards** [maxmind/libmaxminddb#218]
Disclaimer: I have little to no knowledge on the API. Trying to fix an issue in code I inherited. My question my be silly or off-topic. If so, my apologies. If you could point me to a helpful ressource (even in the "silly" case), I would still appreciate that ;-)

I have the problem that the json part of the API return code does not contain spaces inside the City name where as the "non-json" part does. This is related to rsyslog issue https://github.com/rsyslog/rsyslog/issues/1650#issuecomment-545851568 (link points to relevant problem statement).

I am pretty sure we do something wrong, but I have no idea what it is and how to do it correctly. Any help would be appreciated.

**Comment by oschwald** [comment]
`libmaxminddb` doesn't provide a function that returns JSON. Looking at rsyslog, it appears to be using `MMDB_dump_entry_data_list`, which is the debug format used by `mmdblookup`. This is not intended to produce valid JSON or be used for anything but dumping debug data.

It then massages that into something JSON like using `str_split`. It loses the whitespace while doing that:

https://github.com/rsyslog/rsyslog/blob/1f8f621a97df6b1989e1aebd8cb15cd6a552fa9c/plugins/mmdblookup/mmdblookup.c#L305-L306

It then parses the JSON it produces.

This all is quite inefficient, it would be much better to use the data provided by `libmaxminddb` directly rather going from that to a debug string to JSON and then parsing that JSON and using it.

**Comment by rgerhards** [comment]
thanks for the great reply and the suggestions (and sry I could answer just today)! I'll now dig deeper into it.

**Comment by rgerhards** [comment]
@oschwald once again many thanks for your comment! If it isn't too much effort, could you just give me a hint which API function I should use to obtain the city? I have "fixed" the current code keeping all its badness, but would like to see if I can move it forward to a clean solution.
