### ISSUE TITLE
Error while installing libmaxminddb

### ISSUE THREAD

**Issue by prakash9999in** [maxmind/libmaxminddb#220]
Error while installing libmaxminddb as per the given installation steps

I am getting the below errors:

**-bash: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.**

The configure and Makefile is missing it seems.

Am I missing something?

Thanks in advance for your help

**Comment by oschwald** [comment]
It appears you downloaded the GitHub-generated tarball rather than the named release. Try https://github.com/maxmind/libmaxminddb/releases/download/1.4.2/libmaxminddb-1.4.2.tar.gz instead.

**Comment by prakash9999in** [comment]
> It appears you downloaded the GitHub-generated tarball rather than the named release. Try https://github.com/maxmind/libmaxminddb/releases/download/1.4.2/libmaxminddb-1.4.2.tar.gz instead.

Thanks @oschwald for your prompt response on this.
Yes I was using the tarball. Your instruction helped.

Thanks again.
