### ISSUE TITLE
pubkey.gpg to import to check rpm ?

### ISSUE THREAD

**Issue by phbfr** [maxmind/libmaxminddb#221]
Hello, 

I would like to verify my "libmaxminddb-1.1.1-5.el6.x86_64.rpm" to upgrade syslog-ng from 3.7 to 3.19... but 

rpm -K libmaxminddb-1.1.1-5.el6.x86_64.rpm

gives output :

RSA sha1 ((MD5) PGP) md5 PAS OK (CLES MANQUANTES: (MD5) PGP#0608b895) 

Is there a pubkey.gpg which i could import to check this rpm ? 

Thanks in advance. 
Philippe

**Comment by oschwald** [comment]
We don't provide RPMs for libmaxminddb. You will need to ask the maintainer of the particular package you are using.
