### ISSUE TITLE
I don 't correctly build the library in Visual Studio 2013  and connect it 

### ISSUE THREAD

**Issue by SavoshkaSergey** [maxmind/libmaxminddb#222]
I downloaded the release " libmaxminddb-1.4.2.tar.gz". Launched the "VS12/libmaxminddb.sln" and created libmaxminddb.lib. Only the "libmaxminddb.lib" should appear? Without libmaxminddb.dll? When connecting the "libmaxminddb.lib" to project with the folder "/include " I get errors
![Безымянный](https://user-images.githubusercontent.com/60940853/76341518-3a7a3180-630e-11ea-910b-8176cf37876e.png)

Please help me . Visual Studio 2013. Windows 8.1. Sorry for my English

**Comment by oschwald** [comment]
You may need to add `wsock32.lib` and `ws2_32.lib` as linker dependencies.

**Comment by SavoshkaSergey** [comment]
Thank you , but it doesn 't help. New errors appear...
![Безымянный 2](https://user-images.githubusercontent.com/60940853/76523558-ac22be80-6479-11ea-93e7-c951a9b4fe8f.png)

**Comment by SavoshkaSergey** [comment]
Only "Lib" should be in the library? 
How to build a library correctly, please tell me.

**Comment by horgh** [comment]
Did you have any success? I think the errors you show are described here - https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?view=vs-2019. I don't know enough about Visual Studio to say how to set this up though. Another thing that might help is we do have some dependencies for Windows listed here - https://github.com/maxmind/libmaxminddb/blob/master/projects/test.vcxproj.template#L63.

**Comment by SavoshkaSergey** [comment]
Thanks for the answer. Unfortunately, no progress has been made so far

**Comment by SavoshkaSergey** [comment]
The problem was resolved after being included in the code: "#pragma comment(lib, "ws2_32.lib")". Thank you very much for your feedback

**Comment by horgh** [comment]
Awesome, glad you figured it out! Thank you for letting us know.
