### ISSUE TITLE
Bad GeoIP2-City.mmdb lookup: MMDB_entry_data_s contains illogical data_size and type

### ISSUE THREAD

**Issue by adiariel** [maxmind/libmaxminddb#223]
**Environment is CenOS 6.0
libmaxmind 1.4.2**

Flow: 
MMDB_SUCCESS == MMDB_open ()
MMDB_lookup_string(): 0 != gai_error and MMDB_SUCCESS != mmdb_error

And than:

	MMDB_entry_data_s countryData = { 0 };
	int status = MMDB_get_value(&(result.entry), &countryData, "country", "iso_code", NULL);
	if ((status == 0)
		&& (countryData.has_data) 
		&& (countryData.type == MMDB_DATA_TYPE_UTF8_STRING))
	{
		Country = PooledString(countryData.utf8_string, countryData.utf8_string + countryData.data_size);
	} 
	else
	{
		LOGGER_WARN("Cant fetch Country. status: " << status << ",  countryData.has_data: " 
			<< countryData.has_data << ", countryData.data_size: " << countryData.data_size 
			<< ", countryData.type: " << countryData.type);
	}

Produces this log:

WARN 12 Mar 2020 09:26:35.802 IPV6: [21122:139928515954624]: GeoIP2Helper.cpp:102[getRegionByAddress]: Cant fetch Country. status: 0,  countryData.has_data: true, countryData.data_size: 178, countryData.type: 181

**Problem: Expecting data_size and type to be 2 (two chars, utf8 type).**

**More information:**
1. Failed on Linux, works OK on Windows 32 compilation
2. Tested with 3 different file – same results.
3. Dumping the results, as MMDB_entry_data_list_s as a big json-like buffer succeeded on all platforms. I see the entries are there.
4. May be memory/types/compilation issue.

Thanks,
Adi Ariel
Viber Media Backend Team

**Comment by oschwald** [comment]
I transfered this issue to the `libmaxminddb` repo.

**Comment by dlannan-fmad** [comment]
I think I am experiencing possibly similar issues using this library with the newest (just downloaded yesterday) dataset. 
Using the database file: GeoLite2-City_20200324/GeoLite2-City.mmdb
I get no region or city info when requesting many IP's and many locations are just weird output (using the dump command)
```
   "location": 
     {
       "accuracy_radius": 
         1000 <uint16>
       "latitude": 
         -10438338752435293719890396892364917466034237982391852769671753509138391401692727071305276655652957403267921171166357211007787457982082232415147751983543405421651415273570304.000000 <double>
       "longitude": 
         -42029518960714173967511149898952791355703658664524365092525892829929582366361896852838699116510557539686137405216059736665188229254480322912253548547040717496190687696641935490208203941530143326417536153165834233481084259117354155501950172492806175871068540189034485383168.000000 <double>
       "time_zone": 
         "America/Chicago" <utf8_string>
     }
```
Im not sure what is going on. Im using a very simple string lookup for an IP.
Shouldnt the location be nulled if its invalid? And also, why is there no city?
This is the output using an online tool:
```
Continent: North AmericaCountry: United StatesCountry Code: USCountry CF: 86Region: SouthwestState: CaliforniaState Code: CaState CF: 73DMA: 807MSA: 41860City: BurlingamePostal Code: 94010Timezone: GMT-08:00Area Code: 650City CF: 61Latitude: 37.56783Longitude: -122.36945
```
Do I need to use an older database?

**Comment by dlannan-fmad** [comment]
After digging around to find an older database. This is now working. It would appear there are some changes in the DB structure that are not reflected in the C library code.

**Comment by dlannan-fmad** [comment]
The problem turned out to be the definition of "MMDB_LITTLE_ENDIAN"
Seems its used only on floats and doubles in functions: 
get_ieee754_float
get_ieee754_double
Enabling this on the Linux box (x86_64 Intel i7) made the databases work - City was available and lat and lon worked (where applicable).

**Comment by oschwald** [comment]
@dlannan-fmad, I moved your issue to https://github.com/maxmind/libmaxminddb/issues/224, as I think it is separate from this one.

**Comment by adiariel** [comment]
Issue solved by compiling libmaxminddb source C files within my code.
That is, by embedding sources in my main compilation directories, and not by a separately compile into a lib.

Thank you All (:

**Comment by oschwald** [comment]
@adiariel, thanks for the update! I am going to go ahead and close this issue, but I am happy to reopen if there are any new details or recurrences.
