### ISSUE TITLE
the file in Release and tag is different

### ISSUE THREAD

**Issue by SKIYET** [maxmind/libmaxminddb#231]
The 1.4.2.tar.gz in Release page and tag page is not same.
There is nothing in the folder ./t/libtap if the 1.4.2.tar.gz is download from tag page

**Comment by oschwald** [comment]
Please use the versioned release tarball, e.g., [libmaxminddb-1.4.2.tar.gz](https://github.com/maxmind/libmaxminddb/releases/download/1.4.2/libmaxminddb-1.4.2.tar.gz). The other links are generated by GitHub and we do not have control over them.
