### ISSUE TITLE
how to extract return?

### ISSUE THREAD

**Issue by omexlu** [maxmind/libmaxminddb#234]
Hello,

At the moment I extract the iso_code as follows:
`/usr/bin/mmdblookup -f /var/lib/GeoIP/GeoLite2-Country.mmdb -i IP country iso_code | sed 's/[^"]*"\([^"]*\)".*/\1/' | xargs`

Is there a clean/effective other way to only get the iso_code (ex. US) as return?

PS. Use the code in a bash script.

Thanks in advance.

**Comment by klp2** [comment]
[mmdbinspect](https://github.com/maxmind/mmdbinspect) should make this easier. For this particular lookup, I would combine it with [jq](https://stedolan.github.io/jq/) for something like:

```
$ mmdbinspect -db /usr/local/share/GeoIP/GeoLite2-Country.mmdb 8.8.8.8 | jq -r '.[].Records[].Record.country.iso_code'
US
```

**Comment by omexlu** [comment]
Works like a charm :)

But i think mmdbinspect must be updated manually over the file provided by github?
