### ISSUE TITLE
Working with ASN-info only

### ISSUE THREAD

**Issue by gvanem** [maxmind/libmaxminddb#244]
All the examples and documentation are based around looking up IP-addresses and what country, location etc.
they are associated with. I'm trying to simply get the name associated with an AS-number without involving IP-addresses.

Should be simply enough? In my little [test-program](https://gist.github.com/gvanem/1619dcd3d3f5033ac0454a3ef19a0b32), in function [`get_asn_data()`](https://gist.github.com/gvanem/1619dcd3d3f5033ac0454a3ef19a0b32#file-test-mmdb-c-L81), I lookup the AS-name using `"autonomous_system_organization"` and the AS-number using `"autonomous_system_number"`
as the `path[0]` to `MMDB_aget_value()`.  It works fine with an ASN data-file from [DB-IP](https://db-ip.com/db/download/ip-to-asn-lite).

But I want to avoid looking up the IP first. So in that case, what should the `MMDB_entry_s *const entry` contain?

In e.g. [IPFire's](https://location.ipfire.org/how-to-use) excellent Python tool, I can simply do:
 > `py -3 location.py get-as 2119`

and it replies:

> `AS2119 belongs to Telenor Norge AS`

Not so easy using `mmdblookup`.

**Comment by oschwald** [comment]
The database doesn't store information in such a way that you can query by ASN. You would need to iterate over the entire data section.
