### ISSUE TITLE
Right way to use FetchContent to download and build for a custom project

### ISSUE THREAD

**Issue by ncoder-1** [maxmind/libmaxminddb#250]
Hi,

I'm trying to build a sample project using CMake's `FetchContent`.  I'm using the following block to pull and build the library so I can use it with my sample project:

```
include(FetchContent)
FetchContent_Declare(
        maxminddb
        GIT_REPOSITORY https://github.com/maxmind/libmaxminddb.git
        GIT_TAG 1.5.0
)
FetchContent_MakeAvailable(maxminddb)
```

Normally, a similar block works for other projects out there, but I'm getting the following CMake errors:

```
CMake Error in build/_deps/maxminddb-src/CMakeLists.txt:
  Target "maxminddb" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/tmp/test/test-lookup/build/_deps/maxminddb-src/"

  which is prefixed in the build directory.


CMake Error in build/_deps/maxminddb-src/CMakeLists.txt:
  Target "maxminddb" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/tmp/test/test-lookup/build/_deps/maxminddb-src/"

  which is prefixed in the build directory.Target "maxminddb"
  INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/tmp/test/test-lookup/build/_deps/maxminddb-src/"

  which is prefixed in the source directory.
```

What is the right way to use `FetchContent` within my own `CMakeLists.txt` to fetch, build and make `libmaxminddb` available for my own project?

**Comment by oschwald** [comment]
I only have limited CMake experience, but perhaps @bsergean would be able to provide some directions. In #243, he significantly reworked the CMake build and I think better `FetchContent` support was a motivation.

**Comment by bsergean** [comment]
Well maybe those changes were not sufficient ... I actually haven't tested it yet, I hope I can find time soon to do so but that's unclear ...

@ncoder-1 maybe you can try with ExternalProject_Add too.

**Comment by bsergean** [comment]
https://cmake.org/cmake/help/latest/module/ExternalProject.html

**Comment by ncoder-1** [comment]
I've tried with ExternalProjects, I got it working but the issue is that ExternalProject doesn't build until I build my own project (explained [here](https://www.scivision.dev/cmake-fetchcontent-vs-external-project/#:~:text=CMake%20FetchContent%20comingles%20the%20CMake,use%20ExternalProject%20instead%20of%20FetchContent.)).

This causes issues with the IDE not being able to index properly and basically turns the syntax autocorrection into a nightmare.

**Comment by oschwald** [comment]
@ncoder-1, from what I can tell, 1.6.0 fixes this. Please let me know if this is not the case.
