### ISSUE TITLE
Macro `_POSIX_C_SOURCE` breaks compilation on macOS

### ISSUE THREAD

**Issue by disigma** [maxmind/libmaxminddb#267]
The definition of macro `_POSIX_C_SOURCE` makes some types in macOS undefined.
https://github.com/maxmind/libmaxminddb/blob/d918412fe7d514108d01e346a832d51e5ccf83c0/include/maxminddb.h#L17

I got the following compilation error messages:
```
/xxxx/usr/include/sys/ucred.h:101:2: error: unknown type name 'u_int'
        u_int   cr_version;             /* structure layout version */
        ^
```

See the https://stackoverflow.com/questions/15393905/c-pcap-library-unknown-types-error , the error is caused by definition of macro `_POSIX_SOURCE`.

Is it necessary to define this macro? Can it be removed?

**Comment by horgh** [comment]
Yeah, we want it.

Adding this to your code may work (I'm not sure):

```c
#include <sys/types.h>
```
