### ISSUE TITLE
Can't solve dependence on libtap

### ISSUE THREAD

**Issue by ocgltd** [maxmind/libmaxminddb#279]
I downloaded the ZIP for this project and make is failing because of the absence of libtap/tap.h

I figured out that was a seperate project, so I downloaded it and symlinked it to libtap in the maxmind directory.  (I assume that's an ok solution).  However, now make fails like this

```
[make[2]: Leaving directory `/data/development/MyLibs/tl_geoip/libmaxminddb-1.6.0/bin'
Making all in t
make[2]: Entering directory `/data/development/MyLibs/tl_geoip/libmaxminddb-1.6.0/t'
cd libtap && make  all
make[3]: Entering directory `/data/development/MyLibs/tl_geoip/libmaxminddb-1.6.0/t/libtap'
make[3]: *** No rule to make target `all'.  Stop.
make[3]: Leaving directory `/data/development/MyLibs/tl_geoip/libmaxminddb-1.6.0/t/libtap'
make[2]: *** [all-local] Error 2
make[2]: Leaving directory `/data/development/MyLibs/tl_geoip/libmaxminddb-1.6.0/t'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/data/development/MyLibs/tl_geoip/libmaxminddb-1.6.0'
make: *** [all] Error 2]
```

The '/data/development/MyLibs/tl_geoip/libmaxminddb-1.6.0/t/libtap' directory is empty.

I have no idea how to solve this.  Can someone offer a solution?  (And perhaps add to docs to help the newbies).  A google search suggested that libtap was just for testing, but I have no idea how to turn off this dependency.

**Comment by oschwald** [comment]
The zip file is generated by GitHub and we have no control over it. Please download the named release `tar.gz` file, e.g., [`libmaxminddb-1.6.0.tar.gz'](https://github.com/maxmind/libmaxminddb/releases/download/1.6.0/libmaxminddb-1.6.0.tar.gz).
