### ISSUE TITLE
'maxminddb.h' not found

### ISSUE THREAD

**Issue by robertocarta** [maxmind/libmaxminddb#290]
Not sure if this is the right repo to post this issue. 
I'm getting the following when running `pip3 install maxminddb --force-reinstall --verbose`.
I checked /usr/local/include/ as recommended in another issue and it does contain the header file. 

`  creating build/temp.macosx-12-x86_64-3.9/extension
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c extension/maxminddb.c -o build/temp.macosx-12-x86_64-3.9/extension/maxminddb.o -Wall -Wextra
  extension/maxminddb.c:3:10: fatal error: 'maxminddb.h' file not found
  #include <maxminddb.h>
           ^~~~~~~~~~~~~
  1 error generated.`

Running MacOS 12.1

**Comment by oschwald** [comment]
This is probably a more appropriate question for StackOverflow. You likely need to set your library and include search paths to include `/usr/local`.

**Comment by robertocarta** [comment]
Thanks. In case somebody gets here with the same issue. The problem is that the compile command is 
  `clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c extension/maxminddb.c -o build/temp.macosx-12-x86_64-3.9/extension/maxminddb.o -Wall -Wextra`
instead of
  `clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/**3.9.10**include/python3.9 -c extension/maxminddb.c -o build/temp.macosx-12-x86_64-3.9/extension/maxminddb.o -Wall -Wextra`


A fix is to install maxminddb with the following flags

` pip install maxminddb --force-reinstall --verbose --no-cache-dir --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib"`
