### ISSUE TITLE
Not able to parse json output with 'jq' command.

### ISSUE THREAD

**Issue by thombr03** [maxmind/libmaxminddb#299]
jq - Command-line JSON processor

$ mmdblookup --file /usr/share/GeoIP/GeoIP2-Country.mmdb --ip 8.8.8.8 | jq
parse error: Invalid numeric literal at line 7, column 0

**Comment by oalders** [comment]
I can reproduce this with `jq-1.6`.

**Comment by oalders** [comment]
@thombr03 I'd encourage you to use `mmdbinspect` instead:

```
mmdbinspect -db usr/share/GeoIP/GeoIP2-Country.mmdb /usr/local/share/GeoIP/GeoIP2-Country.mmdb 8.8.8.8 | jq
```

See https://github.com/maxmind/mmdbinspect#installation
