### ISSUE TITLE
jq fails to parse the json output

### ISSUE THREAD

**Issue by SkyperTHC** [maxmind/libmaxminddb#307]
Doesnt look like it's json but only 'json-like':

# mmdblookup --file /GeoLite2-City_20220930/GeoLite2-City.mmdb --ip 1.1.1.1 | jq
parse error: Invalid numeric literal at line 7, column 0

**Comment by oschwald** [comment]
`mmdblookup` does not output JSON. As you note, the output is only JSON-like. The tool is primarily targeted towards developers integrating `libmaxmindb` into their application. If you want JSON in a tool aimed at end users, please use [`mmdbinspect`](https://github.com/maxmind/mmdbinspect).
