### ISSUE TITLE
Anonymous functionality in c api

### ISSUE THREAD

**Issue by asayupteam** [maxmind/libmaxminddb#309]
Looks like C API does not have anonymous ip detection implemented.
If its there can you please point me to example or doc explaining usage.

**Comment by oschwald** [comment]
This library supports any database in the MMDB format. Please see the [API docs](https://github.com/maxmind/libmaxminddb/blob/main/doc/libmaxminddb.md) for information on how to use it. Depending on your use case, there are several different ways you could use it for any particular database. For looking up particular values by their keys, I would recommend the [data lookup functions](https://github.com/maxmind/libmaxminddb/blob/main/doc/libmaxminddb.md#data-lookup-functions). Please feel free to reach out to [support@maxmind.com](mailto:support@maxmind.com) for additional help.
