### ISSUE TITLE
comparing results of IP countries

### ISSUE THREAD

**Issue by tbswork1** [maxmind/libmaxminddb#311]
I used a project to test the IP country returned by libmaxminddb's Geolite2 Country (2020-08-07) and ip2location's Lite IP-Country (2022-10-29) on 10K random IPs and get the attached results. There are many IP being resolved in different countries. And how to known which is correct? Thanks. 

(I am trying to verify the advertised accuracy of maxmind's 99.8% vs ip2location's 98%.)

[country_test_ipv4_data_mass_ip2location_res.txt](https://github.com/maxmind/libmaxminddb/files/9937980/country_test_ipv4_data_mass_ip2location_res.txt)
[country_test_ipv4_data_mass_maxmind_res.txt](https://github.com/maxmind/libmaxminddb/files/9937982/country_test_ipv4_data_mass_maxmind_res.txt)

**Comment by oschwald** [comment]
This repo is just for the C library, not any particular data set. I'd encourage you to reach out to [support@maxmind.com](mailto:support@maxmind.com) with questions about the data.

That said, if I were trying to compare two databases, I would start with a list of IPs where I know the location and compare the results. If you don't know the locations, it will be difficult to determine which is correct. If you are using random IPs, it is also likely that some of the difference are for IPs that are not actually in use where the correct answer is less clearly defined.
