### ISSUE TITLE
Help configure build parameters for building on Windows

### ISSUE THREAD

**Issue by nezdolik** [maxmind/libmaxminddb#321]
Hi, I have encountered difficulties configuring build of libmaxmind on Windows (for [Envoy integration](https://github.com/envoyproxy/envoy/pull/28490/files#diff-b41c4b58d2c12b8e10909bbaceadd6b63640b30aea3f9cc9cedad2777a6173f2)). Could you help me validate few things:
* The produced artefact name, will it be `libmaxminddb.lib` ?
* Any windows specific flags, that need to be explicitly set? I have added `"WIN32": "yes"` so far
* Below flags are used for building on all platforms, perhaps some of those are not suitable for Windows?:
```
        "CMAKE_BUILD_TYPE": "Release",
        "CMAKE_INSTALL_LIBDIR": "lib",
        "CMAKE_CXX_COMPILER_FORCED": "on",
        "BUILD_SHARED_LIBS": "no",
        "BUILD_TESTING": "no",
```

**Comment by oschwald** [comment]
I believe the name would be `maxminddb.lib`. We use the default CMake library prefixes for the platform.

You shouldn't need any particular flags, but it will depend on the particulars of what you are doing.

**Comment by nezdolik** [comment]
Thanks @oschwald, i will fix artefact name, that could potentially be the rootcause of failing build

**Comment by nezdolik** [comment]
Closing this one, the problem got fixed. Thanks!
