### ISSUE TITLE
Does object created from `MMDB_open` further detect mmdb file updates?

### ISSUE THREAD

**Issue by nezdolik** [maxmind/libmaxminddb#322]
Hi, whenever an mmdb file used by a process has been initialized with `MMDB_open` call and the file has been modified in process, would those changes be detected for mmdb object? Or does one need to watch file for update events and to reload mmdb object with  `MMDB_open` call on update event?

**Comment by oschwald** [comment]
No, it does not watch the file for changes. The application would need to watch if it wants hot-reloads of files.

If you are updating the the file while the application is running, I would recommend writing the file atomically so that the old file handle remains valid when the file is updated.

**Comment by nezdolik** [comment]
Thanks @oschwald!
