### ISSUE TITLE
Python vs C extension difference with large db

### ISSUE THREAD

**Issue by suola** [maxmind/libmaxminddb#335]
We have a custom built db with the following details:

- record size: 32
- node count: 542155119
- file size: 4339498906

The database works with python implementation. The latest maxminddb python library came with a vendored copy of `libmaxminddb`, and we noticed that the database doesn't work with the C extension.

Opening the database succeeds, but a query for an IP results in

```
maxminddb.errors.InvalidDatabaseError: Error looking up 192.0.2.0. The MaxMind DB file's search tree is corrupt
```

Slightly smaller database works properly also with the C extension, so maybe the database size is the problem?

**Comment by suola** [comment]
I sent you an email regarding the db file.

We have successfully created the db with the go driver, and will switch from the perl writer to that in the near future.

**Comment by oschwald** [comment]
`maxminddb` 2.5.2 has been released with a fix for this.
