### ISSUE TITLE
Ability to identify iCloud Private Relay not by string comparison

### ISSUE THREAD

**Issue by nezdolik** [maxmind/libmaxminddb#341]
Hi, according to Maxmind [docs](https://blog.maxmind.com/2021/09/data-updates-for-apple-icloud-private-relay/), an IP can be tagged as `iCloud Private Relay` (string value) in ISP database. Would it be possible to introduce a boolean field instead to identify such IPs? For a high traffic load and latency sensitive proxy, it will be wasteful to perform string comparisons on each request.

**Comment by oschwald** [comment]
This repo is specific to this library. I would suggest directing data questions to support@maxmind.com. That said, I would expect the cost of the string comparison to be quite small compared to the cost of the lookup. For both booleans and strings, you could avoid the cost of deserializing by caching the offsets tot he data records.
