### ISSUE TITLE
mmdblookup output is not JSON

### ISSUE THREAD

**Issue by haraldhh** [maxmind/libmaxminddb#344]
I noticed that even though the man-page for mmdblookup talks about "a JSON structure like this" the output of mmdblookup is not properly formatted JSON.

Could it be possible to produce JSON-output so it would be parseable? It would like to print the "iso_code, country name" in a shellscript, and it would be easy with jq if the output would be JSON-formatted.

**Comment by oschwald** [comment]
We provide [mmdbinspect](https://github.com/maxmind/mmdbinspect) for that use case. `mmdblookup` is intended to be used as a database debugging tool. The output includes the types and other information.
