### ISSUE TITLE
t/libtap is empty

### ISSUE THREAD

**Issue by SonnyJim** [maxmind/libmaxminddb#47]
Checked out the repo using this command:
git clone https://github.com/maxmind/libmaxminddb.git

During compilation I get this error:
maxminddb_test_helper.h:13:24: fatal error: libtap/tap.h: No such file or directory

ls t/libtap/ reveals that it's empty

**Comment by bianlizuozishu** [comment]
Hello, I download the latest version of the source code to compile or have the above questions, didn't find what you said can use version, trouble to reply Thank you very much

**Comment by oschwald** [comment]
Please download [libmaxminddb-1.2.0.tar.gz](https://github.com/maxmind/libmaxminddb/releases/download/1.2.0/libmaxminddb-1.2.0.tar.gz) rather than the GitHub generated source archives.

**Comment by bianlizuozishu** [comment]
I am in China, the link failure for me, don't know why. Could you please new upload, thank you very much
https://github.com/maxmind/libmaxminddb/releases/download/1.2.0/libmaxminddb-1.2.0.tar.gz

**Comment by selboo** [comment]
think
