### ISSUE TITLE
Homebrew package not installing as universal

### ISSUE THREAD

**Issue by RR2DO2** [maxmind/libmaxminddb#82]
This is the other end of the problem listed in https://github.com/maxmind/MaxMind-DB-Reader-python/issues/2.

On Yosemite, Homebrew appears to install a 64 bit only version of libmaxminddb. This then will cause the Python extension to fail compile. The workaround is to force a universal install of libmaxminddb through brew (brew install --universal libmaxminddb), but since this is not the default many people won't do this. The bottle is not generated with --universal either.

libmaxminddb should probably always build as universal on OS X to avoid these compatibility issues.

**Comment by oschwald** [comment]
We don't maintain the Homebrew formula ourselves. [Looking at it](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libmaxminddb.rb), it appears to be quite out of date.

**Comment by RR2DO2** [comment]
Since Homebrew is mentioned as a primary installation method in the readme, this is probably something you'll find many OS X/Python user running into. The formula looks quite official as well and has no maintainer information, so posting here seems to be the best bet - especially since the linked github issue at maxmind-db-reader-python mentions official releases (though doesn't explicitely state Homebrew).  If Homebrew keeps the recommended way of installing it on OS X (and probably should), then it might make sense to take over maintaining it as part of the project?

**Comment by oschwald** [comment]
Yeah, I agree that it would make sense for us to submit PRs to update it regularly or remove it from the README. However, I am not sure what their policy is on universal binaries. It might best to create an issue there and link to it from here.

**Comment by RR2DO2** [comment]
So I've chased this up with the Homebrew people and it looks like this won't chase there or here, what appears to be the desired case is that the installation of the Python package won't fail on missing 32 bit binaries. This should then probably be taken back to the original Python package thread.

**Comment by oschwald** [comment]
Closing as there is an issue downstream in Homebrew to track this.
