### ISSUE TITLE
where is configure

### ISSUE THREAD

**Issue by benno233** [maxmind/libmaxminddb#84]
I see U document,But not configure file in download,Please check!

**Comment by oschwald** [comment]
Please download [libmaxmind-1.0.4.tar.gz](https://github.com/maxmind/libmaxminddb/releases/download/1.0.4/libmaxminddb-1.0.4.tar.gz) from the [releases page](https://github.com/maxmind/libmaxminddb/releases). Only the release dists have the configure script.
