### ISSUE TITLE
libtap/tap.c:327: error: ‘MAP_ANONYMOUS’ undeclared (first use in this function) 

### ISSUE THREAD

**Issue by yiliaofan** [maxmind/libmaxminddb#85]
libtap/tap.c:327: error: ‘MAP_ANONYMOUS’ undeclared (first use in this function) #77

please help, thanks!

gcc -v:
 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-amazon-linux/4.8.2/lto-wrapper
Target: x86_64-amazon-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,fortran,ada,lto --enable-plugin --enable-initfini-array --disable-libgcj --without-isl --without-cloog --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-amazon-linux
Thread model: posix
gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) 
 
[root@iZ250swn6k1Z ext]# uname -a
Linux ip-172-31-10-100 3.14.35-28.38.amzn1.x86_64 #1 SMP Wed Mar 11 22:50:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yiliaofan** [comment]
#define __USE_MISC
#include <bits/mman.h>

add ，then solve the problem

**Comment by autarch** [comment]
We import this using a git submodule of https://github.com/zorgnax/libtap. Would you mind filing the bug report there?
