### ISSUE TITLE
Warnings when building

### ISSUE THREAD

**Issue by Ironholds** [maxmind/libmaxminddb#86]
Building in Clang as part of a distinct package, rgeolocate, we get [these warnings](https://github.com/Ironholds/rgeolocate/issues/11). They appear to be in libmaxminddb; any idea?

**Comment by oschwald** [comment]
Do you get these warnings when building libmaxminddb directly? What version of clang are you building this and what compiler flags are you using? I am not seeing the warnings in our [Travis builds with clang](https://travis-ci.org/maxmind/libmaxminddb/jobs/53103010).

**Comment by Ironholds** [comment]
@wrathematics eyup

**Comment by wrathematics** [comment]
We're using the scan-build static analyzer built in with clang.  You can recreate the warnings by cloning `maxmind/libmaxminddb` and running:

```
libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf

export MAKE='scan-build make'
CFLAGS=--std=c11 ./configure
make
```

**Comment by oschwald** [comment]
Ah, that makes for sense. We will look into the warnings.

**Comment by wrathematics** [comment]
If you aren't familiar with scan-build, look for a line like

```
scan-build: Run 'scan-view /tmp/scan-build-2015-07-13-122332-17094-1' to examine bug reports.
```

somewhere after linking.  If you run that, you can see a nice report and interactively follow the logic that leads to the warning.

**Comment by oschwald** [comment]
The tmp variable warning appears to be real but harmless. The other two are false positives. I guess we could add some asserts or something, which would help the static analyzer.

**Comment by Ironholds** [comment]
Thanks!
