### ISSUE TITLE
includedir not respected for maxminddb_config.h

### ISSUE THREAD

**Issue by paravoid** [maxmind/libmaxminddb#89]
In Debian, for co-installation purposes across multiple architectures (a feature called "multi-arch"), it is required that the packages ship identical contents for identical filenames across different architectures.

Since `maxminddb_config.h` varies by architecture (MMDB_UINT128_IS_BYTE_ARRAY is set to 1 on e.g. i386 but 0 on e.g. amd64, assuming recent toolchain), the only way to do this is to ship header files to /usr/include/<architecture triplet/ which is supported by the Debian toolchain as an include path.

I attempted to do so by passing `--includedir` to `configure`, but this resulted into this:
```
-rw-r--r-- root/root      7069 2015-07-19 02:31 ./usr/include/x86_64-linux-gnu/maxminddb.h
-rw-r--r-- root/root      6429 2015-07-19 02:31 ./usr/include/x86_64-linux-gnu/maxminddb-compat-util.h
-rw-r--r-- root/root       507 2015-07-19 02:31 ./usr/include/maxminddb_config.h
```

My autoconf foo isn't great, but the above diff seems to fix this:
```diff
--- a/Makefile.am
+++ b/Makefile.am
@@ -1,7 +1,7 @@
 
 include_HEADERS = include/maxminddb.h src/maxminddb-compat-util.h
 
-include_execdir = $(exec_prefix)/include
+include_execdir = $(includedir)
 
 nodist_include_exec_HEADERS = include/maxminddb_config.h

```

**Comment by oschwald** [comment]
Could you send the `configure` arguments that you are trying to use? The change looks mostly reasonable to me, but I just want to verify the behavior myself.

**Comment by oschwald** [comment]
So I tested this out, and the current use of `--exec-prefix` seems to work for putting architecture-specific files in the correct directory while leaving the others in `PREFIX`. However, this does not map well to how Debian, in particular, lays out the files as it creates a separate architecture specific directory in the general includes directory. Do you have any links that document what Debian considers best practices for library authors when it comes to multiarch support? I assume this is a fairly common issue.

**Comment by paravoid** [comment]
For what it's worth, I was just passing `--includedir="\$${prefix}/include/$(DEB_HOST_MULTIARCH)"`. $DEB_HOST_MULTIARCH is just set to the triplet, e.g. `x86_64-linux-gnu`.

This is necessary because `maxminddb_config.h`'s contents vary between different architectures.

**Comment by oschwald** [comment]
Right. Previously that file was installed to the include directory in the `--exec-prefix` precisely because it was architecture specific. However this was non-standard, creating more confusion and complexity.
