### ISSUE TITLE
undefined macro: AC_PROG_LIBTOOL

### ISSUE THREAD

**Issue by ericgriffis** [maxmind/libmaxminddb#9]
Trying to install on Mac OS X 10.9.1 I get the following error:

```
bash-3.2$ git clone --recursive https://github.com/maxmind/libmaxminddb
bash-3.2$ cd libmaxminddb
bash-3.2$ ./bootstrap
rm: ltmain.sh: No such file or directory
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/Cellar/autoconf/2.69/bin/autoconf --force
configure.ac:14: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
```

What could be the issue? I had installed successfully on another machine using the bz/remove-gnu-extensions branch of the repository, but it appears this branch no longer exists, and I am installing on a separate machine. Is there another branch I should install from?

**Comment by lucamolteni** [comment]
Thanks @borisz that helped me

**Comment by dipenpatel235** [comment]
For centos required to install

yum install libtool

and for ubuntu

apt-get install libtool

**Comment by ziyangfrank** [comment]
main::scan_file() called too early to check prototype at /usr/local/bin/aclocal line 617.
configure.ac:30: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1


I have use suo apt-get install libtool.but can't slove this issue,and the libtool version is  libtool (GNU libtool) 2.4.2
 can you help me ?

**Comment by oschwald** [comment]
@ziyangfrank, if you are using our release tarballs, eg., [libmaxminddb-1.3.2.tar.gz](https://github.com/maxmind/libmaxminddb/releases/download/1.3.2/libmaxminddb-1.3.2.tar.gz), you shouldn't need to run the boostrap script or need libtool installed.

**Comment by rayss1** [comment]
I have libtool installed by brew install libtool, but I still get this error

**Comment by oschwald** [comment]
@rayss1, as advised above, you should be using the versioned release tarballs, which don't require running the bootstrap script. For instance, [libmaxminddb-1.4.2.tar.gz](https://github.com/maxmind/libmaxminddb/releases/download/1.4.2/libmaxminddb-1.4.2.tar.gz) for the current release.
