### ISSUE TITLE
So close to actual JSON

### ISSUE THREAD

**Issue by fxfactorial** [maxmind/libmaxminddb#92]
I am writing OCaml bindings to libmaxminddb and wondering why the library doesn't actually provide JSON. I mean `dump_entry_data_list` is already so close to valid JSON, so why not go the extra step and make it actual JSON.

**Comment by oschwald** [comment]
Cool, I look forward to seeing the OCaml bindings!

As for that function, the primary purpose is to dump the data, including the type metadata, for debugging purposes. Although we could provide a function that does produce valid JSON, it would be sub-optimal for using in bindings of the sort that you are working on. Serializing and deserializing the data is slow, and you would lose all of the type information.

**Comment by fxfactorial** [comment]
Okay, understood. 

FWIW the bindings are here: https://github.com/fxfactorial/ocaml-maxminddb.

**Comment by oschwald** [comment]
Nice. Is it on OPAM yet?

**Comment by fxfactorial** [comment]
Waiting on opam repo people to accept PR, make; make install should work just fine or an opam pin.

**Comment by fxfactorial** [comment]
FWIW, its up on opam. `opam install maxminddb`. I think its pretty stable too.

**Comment by oschwald** [comment]
Cool. I added it to our [list of third party APIs](http://dev.maxmind.com/geoip/geoip2/downloadable/#Third-Party_APIs).

**Comment by PatrickCronin** [comment]
_Digging up the past a bit, but for posterity:_

We have recently released  [https://github.com/maxmind/mmdbinspect](`mmdbinspect`) which is a new tool intended to address several of the issues people raised relating to the general usability of `mmdblookup`. It supports querying multiple databases and multiple IPs with a single incantation, and it outputs pure JSON.

While the intent of `mmdblookup` was and is to support developers who are integrating libmaxminddb or other reader libraries into their applications, `mmdbinspect` is intended to be a well-behaved command line program supporting general purpose querying of MMDB databases.

It's in beta. We would welcome you to try it and provide any feedback you may have on its issues page.
