### ISSUE TITLE
Missing maxminddb packages for vivid

### ISSUE THREAD

**Issue by adq** [maxmind/libmaxminddb#93]
Hi, the prebuilt maxminddb packages for vivid are missing from your ppa. I can see the geoip libs in there, but not libmaxminddb0, libmaxminddb-dev, mmdb-bin.

See: http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/vivid/main/binary-amd64/Packages

**Comment by oschwald** [comment]
Thanks for bringing this up. I'll make sure they get generated the next time we do a build.

**Comment by megahall** [comment]
I wanted to ping this bug and see if it could be fixed soon.

**Comment by kris** [comment]
+1

**Comment by spoekie** [comment]
ja er ging iets verkeerd

**Comment by oschwald** [comment]
These are available now for Wily and Vivid. They were not rebuilt but merely copied over from Utopic.
